name: MigTool continuous build
# read more here
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - '*'
      - '!refs/tags/.*'
    tags-ignore:
      - '*'

jobs:
  build:
    name: Tower build
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64

      - name: Tests
        run: ./gradlew check
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOWER_CI_AWS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOWER_CI_AWS_SECRET }}

      - name: Release
        if: "contains(github.event.head_commit.message, '[release]')"
        run: ./gradle.sh clean buildInfo test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOWER_CI_AWS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOWER_CI_AWS_SECRET }}
